name: local_entity_provider

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core_packages/core
  utils:
    path: ../../packages/utils

  path_provider: ^2.1.4
  win32: ^5.7.1
