name: theme

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  storage:
    path: ../../packages/storage
  utils:
    path: ../../packages/utils

  system_theme: ^3.1.2
