name: utils

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  fluda: ^1.1.0
  universal_platform: ^1.1.0
  mime: ^2.0.0
  path:
  easy_debounce: ^2.0.3
